project:
  type: website

website:
  title: "CSCi 3907"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - schedule.qmd
      - policies.qmd
      - weekly.qmd
      - resources.qmd
      - instructor.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true



