---
title: "Resources"
format: html
---

<!--- Example of card -->
<!-- Tip: use bg-* and text-* utilities to style the card -->

<div class="card text-white bg-primary mb-3 d-inline-block" style="max-width: 20rem;">
<div class="card-header">IoT & Edge Compute video sources</div>
<div class="card-body">
<!-- <h4 class="card-title"></h4> --> 
<h6 class="card-title">Disclaimer: The instructor has no commercial or personal interest in the companies or individual entities in the videos. These videos showcase IoT and Edge Compute examples for general interest.</h6>
<p>Talking Tech: Zipcar and iPhone <a href="https://www.youtube.com/watch?v=rCO0jFoJ1xY" style="color:blue;" target="_blank">https://www.youtube.com/watch?v=rCO0jFoJ1xY</a></p>
<p>Combining AI, 5G, And Machine Vision To Transform Fish Farming <a href="https://youtu.be/PzQ_iWKFsxE" style="color:blue;" target="_blank">https://youtu.be/PzQ_iWKFsxE</a></p>  
<p>What Is the Internet of Things and Why Should You Care? | MIT Sloan <a href="https://www.youtube.com/watch?v=_l75CrN-hSI" style="color:blue;" target="_blank">https://www.youtube.com/watch?v=_l75CrN-hSI</a></p>
<p>What is Edge computing?  <a href="https://www.youtube.com/watch?v=3hScMLH7B4o&t=6s" style="color:blue;" target="_blank">https://www.youtube.com/watch?v=3hScMLH7B4o&t=6s</a></p>
</div>
</div>

<div class="card text-white bg-primary mb-3 d-inline-block" style="max-width: 20rem;">
<div class="card-header">Python programming video sources</div>
<div class="card-body">
<!-- <h4 class="card-title"></h4> --> 
<h6 class="card-title">Disclaimer: The instructor has no commercial or personal interest in the companies or individual entities in the videos. These videos showcase programming paradigms for general interest.</h6>
<p>What is a programming language ?<a href="https://www.youtube.com/watch?v=EGQh5SZctaE" style="color:blue;" target="_blank">https://www.youtube.com/watch?v=EGQh5SZctaE</a></p>
<p>Sequences, Selections, and Loops: <a href="https://youtu.be/eSYeHlwDCNA" style="color:blue;" target="_blank">https://youtu.be/eSYeHlwDCNA</a></p>  
<p>Loops: <a href="https://youtu.be/wxds6MAtUQ0" style="color:blue;" target="_blank">https://youtu.be/wxds6MAtUQ0</a></p>
<p>for-loop: <a href="https://youtu.be/EfJVnAHiR4s" style="color:blue;" target="_blank">https://youtu.be/EfJVnAHiR4s</a></p>
</div>
</div>

<div class="card text-white bg-primary mb-3 d-inline-block" style="max-width: 20rem;">
<div class="card-header">Report templates</div>
<div class="card-body">
<h4 class="card-title">Documents</h4>
<p>NSF-style proposal template: <a href="https://github.com/jeremygibbs/nsf-proposal-latex" style="color:blue;" target="_blank">An NSF proposal template in LaTeX-WTFPL license</a></p>
</div>
</div>

<!-- 
<div class="card text-white bg-dark mb-3 d-inline-block" style="max-width: 20rem;">
<div class="card-header">Presentation templates</div>
<div class="card-body">
<h4 class="card-title">Primary card title</h4>
<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
</div>
</div>
-->