---
title: "Schedule"
format: html
---

Sample class schedule [week-by-week]

(The course schedule subject to changes during the semester)

<table class="table table-hover w-auto">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Topic(s) and readings </th>
      <th scope="col">$\mu$-LABs and Assignment(s) due</th>
      <!--- <th scope="col">Column heading</th> -->
    </tr>
  </thead>
  <tbody>
    <tr class="table-active">
      <th scope="row">Week 1 [01/20/2023]</th>
      <td>
        <ul>
          <li>IoT and Edge Computing [The big pictures]</li> 
          <li>Introduction to Raspberry Pi and Python programming</li> 
          <li>Course overview, policies and deliverables</li>
          <li><a href="https://drive.google.com/drive/folders/1qYaXJ_VKJUxnIOQKGn9c_LDQjJIzSsWs?usp=sharing" target="_blank">Lecture notes</a></li> 
        </ul>  
      </td>
      <td>
        <ul>
          <li>Getting familiar with the Raspberry Pi 3B+</li>
          <li>Python programming using Thonny</li> 
        </ul>
      </td>
      <td>
      </td>
      <!--- <td>Column content</td> -->
    </tr>
    <tr>
      <th scope="row">Week 2 [01/27/2023]</th>
      <td>
        <ul>
          <li>Overview of computing in IoT</li>
          <li>Differences in Cloud and Fog computing</li>
          <li>What is Edge Computing and Edge Compute device</li>
          <li><a href="https://drive.google.com/drive/folders/1qYaXJ_VKJUxnIOQKGn9c_LDQjJIzSsWs?usp=sharing" target="_blank">Lecture notes</a></li> 
        </ul>
      </td>
      <td>
        <ul>
          <li>Setting up the Edge Lab</li>
          <li>Understanding the Python installation on the Raspberry Pi</li>
          <li>Some basic Python programming constructs</li>
          <li>First steps in Raspberry Pi programming [Blinking LEDs]</li>
          <li><a href="https://drive.google.com/drive/folders/1nfW_e6UMP8V1tn20zKAe9_b9Ix1DTEUw?usp=sharing" target="_blank">Lab examples</a></li> 
          <li><a href="https://drive.google.com/drive/folders/14M0NCkRZcFNnOYdubMGOuJn35kvvJhV2?usp=sharing" target="_blank">HW 1 assigned</li> 
        </ul>
      </td>
      <td>
      </td>
      <!--- <td>Column content</td> -->
    </tr>
    <tr class="table-primary">
      <th scope="row">Week 3 [02/03/2023]</th>
      <td>
        <ul>
          <li>Python skelton code for running programs on the Raspberry Pi</li>
          <li>Recap of some programming constructs</li>
          <li>Using Thonny to blink LEDs</li>
          <li>Using bash script to blink LEDs</li>
          <li> Blinking LEDs on boot</li>
          <li><a href="https://drive.google.com/drive/folders/1qYaXJ_VKJUxnIOQKGn9c_LDQjJIzSsWs?usp=sharing" target="_blank">Lecture notes</a></li> 
        </ul>
      </td>
      <td>
        <ul>
          <li>In-class Raspberry Pi Lab (Blinking LEDs)</li> 
          <li>Setting up a Python virtual environment [venv] and it's benefits</li>
          <li>Installing Python GPIO packages with pip in [venv]</li>
          <li>Configuring the GPIO interface on your Raspberry Pi</li>
          <li><a href="https://drive.google.com/drive/folders/1nfW_e6UMP8V1tn20zKAe9_b9Ix1DTEUw?usp=sharing" target="_blank">Lab examples</a></li> 
          <li>HW 1 due</li>
          <li><a href="https://drive.google.com/drive/folders/1CxLrXRJWuxXs9b0EGe7dtjVMMIDOgh7P?usp=sharing" target="_blank">HW 2 assigned</li> 
        </ul>
      </td>
      <!--- <td>Column content</td> -->
    </tr>
    <tr class="table-secondary">
      <th scope="row">Week 4 [02/10/2023]</th>
      <td>
        <ul>
          <li>IoT Architecture and Ecosystem</li>
          <li>Layers in IoT systems - 3 level  layer model</li>
          <li>Sensors</li>
          <li>Sensor types and considerations</li>
          <li><a href="https://drive.google.com/drive/folders/1qYaXJ_VKJUxnIOQKGn9c_LDQjJIzSsWs?usp=sharing" target="_blank">Lecture notes</a></li> 
        </ul>
      </td>
      <td>
        <ul>
          <li>In-class Raspberry Pi Lab (Ultrasound sensors)</li>
          <li>Proxmity sensing using Thonny IDE</li>
          <li>Proxmity sensing using bash script</li>
          <li>Proxmity sensing on boot</li>
          <li><a href="https://drive.google.com/drive/folders/1nfW_e6UMP8V1tn20zKAe9_b9Ix1DTEUw?usp=sharing" target="_blank">Lab examples</a></li>
          <li>HW 2 due</li>
          <li><a href="https://drive.google.com/drive/folders/1GBfK0bdTBG1bZ6pfE7bMp7C-0M_ezPw5?usp=share_link" target="_blank">HW 3 assigned</li> 
        </ul>
      </td>
      <!--- <td>Column content</td> -->
    </tr>
    <tr class="table-success">
      <th scope="row">Week 5 [02/17/2023]</th>
      <td>
        <ul>
          <li>Actuators</li>
          <li>Actuator types and characteristics</li>
          <li>Guest lecture:  <a href="/Lectures_Speakers/Chowdary-bio-Jan2023.pdf"
          target="_blank">Chowdary  Yanamadala</a>, Technology Strategist <a href="https://arm.com"
          target="_blank">ARM</a></li>
          <li>Practical introduction to MQTT</li>
        </ul>
      </td>
      <td>
        <ul>
          <li>Practical introduction to Cayenne-myDevices <a href="https://developers.mydevices.com/cayenne/features/"target="_blank">, A drag-and-drop IoT project builder</a></li>
          <li>Raspberry Pi LEDs controlled by Cayenne</li>
          <li>In-class Raspberry Pi Lab with senseHAT</li>
          <li>HW 3 due</li>
          <li>HW 4 assinged</li>
          <li>Midterm project released</li>
        </ul>
      </td>
      <!--- <td>Column content</td> -->
    </tr>
    <tr class="table-danger">
      <th scope="row">Week 6 [02/24/2023]</th>
      <td>
        <ul>
          <li>IoT Taxonomy - 5 layer model</li>
          <li>Guest lecture 6.1</li>
        </ul>
      </td>
      <td>
        <ul>
          <li>Working with pandas</li>
          <li>In-class Raspberry Pi Lab on Image Processing</li>
          <li>Working with SciPy</li>
          <li>In-class Raspberry Pi Lab</li>
          <li>HW 4 due</li>
          <li>HW 5 assinged</li>
          <li>Practical introduction to Cayenne-myDevices</li>
        </ul>
      </td>
      <!--- <td>Column content</td> -->
    </tr>
    <tr class="table-warning">
      <th scope="row">Week 7 [03/03/2023]</th>
      <td>
        <ul>
          <li>Using sudo within virtual environments</li>
          <li>Basics of Matrices [Warming up to numerical data]</li>
          <li>Handling data arrays and plotting data using Python</li>
          <li>Working with matplotlib</li>
          <li>Exploring numerical data using matrices</li>
          <li>Understanding Analog and Digital Signals</li>
          <li>Fundamentals of signal visualization in time and frequency</li>
          <li>Guest lecture:  <a href="https://www.seas.gwu.edu/timothy-wood"
          target="_blank">Prof. Tim Wood</a>, Interim Chair, CS Department, GWU. <a href="http://faculty.cs.gwu.edu/timwood/" target="_blank">Director of GW Cloud Systems Lab</a></li>
        </ul>
      </td>
      <td>
        <ul>
          <li>Working with Scikit or Keras </li>
          <li>In-class Raspberry Pi Lab</li>
          <li>HW 5 due</li>
          <li>HW 6 assinged</li>
        </ul>
      </td>
      <!--- <td>Column content</td> -->
    </tr>
    <tr class="table-info">
      <th scope="row">Week 8 [03/10/2023]</th>
      <td>
        <ul>
          <li>Case study: IoT in Vehicular Applications</li>
          <li>Guest lecture:  <a href="/Lectures_Speakers/RJS-bio-Jan2023.pdf" target="_blank">Robert Shaughnessy</a>, Senior Vice President, <a href="https://grimmcyber.com" target="_blank">GRIMM Cyber</a></li>
        </ul>
      </td>
      <td>
        <ul>
          <li>In-class Raspberry Pi Lab</li>
          <li>HW 6 due</li>
          <li>HW 7 assinged</li>
          <li>Final Project - Proposals due</li>
        </ul>
      </td>
      <!--- <td>Column content</td> -->
    </tr>
    <tr class="table-dark">
      <th scope="row">03/13/2022 to 03/17/2023</th>
      <td colspan="2">Spring Break. No class this week</td> 
      <!--- <td>Column content</td> -->
    </tr>
    <tr class="table-light">
      <th scope="row">Week 9 [03/24/2023]</th>
      <td>
        <ul>
          <li>Details on IoT Communication layers</li>
          <li>Guest lecture:  <a href="/Lectures_Speakers/RemyPottier-bio-Jan2023.pdf" target="_blank">Remy Pottier</a>, Director of Innovation, <a href="https://arm.com" target="_blank">ARM</a></li>
        </ul>
      </td>
      <td>
        <ul>
          <li>Practical Introduction to ThingSpeak</li>
          <li>In-class Raspberry Pi Lab</li>
          <li>HW 7 due</li>
          <li>HW 8 assinged</li>
        </ul>
      </td>
      <!--- <td>Column content</td> -->
    </tr>
    <tr class="table-primary">
      <th scope="row">Week 10 [03/31/2023]</th>
      <td>
        <ul>
          <li>Case study - continued </li>
          <li>Guest lecture:  <a href="/Lectures_Speakers/NeerajPaliwal-bio-Jan2023.pdf" target="_blank">Neeraj Paliwal</a>, General Manager and VP of Security IP, <a href="https://www.rambus.com" target="_blank">Rambus</a></li>
        </ul>
      </td>
      <td>
        <ul>
          <li>In-class Raspberry Pi Lab</li>
          <li>HW 8 due</li>
          <li>HW 9 assinged</li>
        </ul>
      </td>
      <!--- <td>Column content</td> -->
    </tr>
    <tr class="table-active">
      <th scope="row">Week 11 [04/07/2023]</th>
      <td>
        <ul>
          <li>Case study: IoT in Healthcare</li>
        </ul>
      </td>
      <td>
        <ul>
          <li>Practical Introduction to IFTTT</li>
          <li>In-class Raspberry Pi Lab</li>
          <li>HW 9 due</li>
          <li>HW 10 assinged</li>
        </ul>
      </td>
      <!--- <td>Column content</td> -->
    </tr>
    <tr class="table-success">
      <th scope="row">Week 12 [04/17/2023]</th>
      <td>
        <ul>
          <li>Case study - continued </li>
          <li>Guest lecture:  <a href="/Lectures_Speakers/ChrisRodley-bio-Jan2023.pdf" target="_blank">Chris Rodley</a>, CEO and founder of Snap Information Technologies (SnapIT), Chairman of Teem Fish Monitoring, Director of Daily Catch and Snap Group LP partner and Tedx speaker, <a href="https://www.snapit.group" target="_blank">SnapIT</a></li>
        </ul>
      </td>
      <td>
        <ul>
          <li>In-class Raspberry Pi Lab</li>
          <li>HW 10 due</li>
          <li>HW 11 assinged</li>
        </ul>
      </td>
      <!--- <td>Column content</td> -->
    </tr>
    <tr class="table-danger">
      <th scope="row">Week 13 [04/21/2023]</th>
      <td>
        <ul>
          <li>Case study: IoT in Environmental monitoring</li>
          <li>Guest lecture 13.1</li>
        </ul>
      </td>
      <td>
        <ul>
          <li>In-class Raspberry Pi Lab</li>
          <li>HW 11 due</li>
          <li>HW 12 assinged</li>
        </ul>
      </td>
      <!--- <td>Column content</td> -->
    </tr>
    <tr class="table-warning">
      <th scope="row">Week 14 [04/28/2023]</th>
      <td>
        <ul>
          <li>Paradigms, Challenges in IoT technologies</li>
        </ul>
      </td>
      <td>
        <ul>
          <li>Final Project Presentations and Demonstrations</li>
          <li>Final Projects due</li>
        </ul>
      </td>
      <!--- <td>Column content</td> -->
    </tr>
    <tr class="table-dark">
      <th colspan="3">NOTE: In accordance with university policy, the final exams will be given during the final exam period and not the last week of the semester</th>
      <!--- <td>Column content</td>
      <td>Column content</td> -->
      <!--- <td>Column content</td> -->
    </tr>
  </tbody>
</table>



<footer>
  <p>This is a Quarto website. To learn more about Quarto websites visit <https://quarto.org/docs/websites>.<br>
  Author: Kartik Bulusu<br>
  Contact: <a href="mailto:bulusu@gwu.edu">bulusu</a><br>
  &copy; 2022 All rights reserved</p>
</footer>
